version: '3.8'

services:
  # The Streamlit Application
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://db:27017/
    depends_on:
      - db

  # The MongoDB Database
  db:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: